server:
  port: 8080

github:
  client:
    id: 1be069a756230d6fc8ab
    secret: 6f221988b88a2aa1a205e76ea6343925be7ee8b8
  redirect:
    url: http://localhost:8080/callback
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url:  jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai
  flyway:
    baseline-on-migrate: true
    enabled: true
  #热部署生效
  devtools:
    restart:
      enabled: false
      #设置重启的目录
      additional-paths: src/main/java,resources/**

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true